const properties =  {
  "1" : { 
    propertyName: "Color",
    displayName: "", 
    description: "", 
    type: "one of", 
    control: "select", 
    options: ["default", "inherit", "primary", "secondary"],
    defaultValue: "primary",
    visible: true,
  },
  "2" : { 
    propertyName: "Children", 
    displayName: "", 
    description: "", 
    type: "node", 
    control: "textarea", 
    defaultValue: "",
    visible: true,
  },
  "3" : { 
    propertyName: "Disabled",
    displayName: "", 
    description: "", 
    type: "boolean", 
    defaultValue: false,
    visible: true,
    },
  "4" : { 
    propertyName: "Disable focus ripple", 
    displayName: "", 
    description: "", 
    type: "boolean", 
    defaultValue: true,
    visible: false,
  },
  "5" : { 
    propertyName: "Disable ripple", 
    displayName: "", 
    description: "", 
    type: "boolean", 
    defaultValue: true,
    visible: false,
  },
  "6" : { 
    propertyName: "Full Width", 
    displayName: "", 
    description: "", 
    type: "boolean", 
    defaultValue: true,
    visible: true,
  },
  "7" : { 
    propertyName: "Mini", 
    displayName: "", 
    description: "", 
    type: "boolean", 
    defaultValue: false,
    visible: false,
  },
  "8" : { 
    propertyName: "Size", 
    displayName: "", 
    description: "", 
    type: "one of", 
    control: "select",
    options: ["default", "small", "medium", "large"],
    defaultValue: "large",
    visible: true,
    },
  "9" : { 
    propertyName: "Variant", 
    displayName: "", 
    description: "", 
    type: "one of", 
    control: "select",
    options: ["default", "text", "outlined", "contained"],
    defaultValue: "contained",
    visible: true,
    },
};

export default properties;